### ISSUE TITLE
Gather logging requirements

### ISSUE THREAD

**Issue by tomdale** [ember-fastboot/ember-cli-fastboot#100]
Right now, logging in the FastBoot server is pretty anemic. It's fine for when things are going well but it's not very helpful if you're trying to track down an error in the Ember app.

I'd like to use this issue as a central place to gather opinions on how we should handle logging in production. In particular, I'm interested in pointers to other Node.js projects that do it well. I also want to make sure we build something sufficiently flexible it can be used with things like AWS CloudWatch, log servers, etc.

**Comment by tomdale** [comment]
@jeffplang is going to write down what he needs

**Comment by jmonster** [comment]
https://github.com/winstonjs/winston is one of the more mature loggers with support for multiple transports. [node-bunyan](https://github.com/trentm/node-bunyan) is very powerful and popular, too.

That said, [hapij.js](http://hapijs.com/) aligns well with ember-cli's plugin architecture; you can read about logging specifically at http://hapijs.com/tutorials/logging . _This would mean not using Express._

Hapijs is a nice way to go because then even ember-cli-addons can tap into the logging system via [hapi plugins](http://hapijs.com/tutorials/plugins). I have an example of such a plugin that listens for particular error types and reports them to Rollbar @ https://github.com/yayuhh/icecreambar/blob/master/index.js#L51-L65 . I'd expect this approach may minimize the effort it takes for FastBoot to enable ember-cli-addons to hook into and extend the server, beyond just logging, if that's on the agenda?

**Comment by hunterloftis** [comment]
Some of the most successful logging I see on Heroku is organized with [debug](https://github.com/visionmedia/debug) for visibility and [logfmt](https://github.com/csquared/node-logfmt) for machine-readability.

Debug is the standard node logging mechanism, used like this:

```
DEBUG=* node server.js  # log everything
DEBUG=express:* node server.js  # log anything from express
DEBUG=myApp:someComponent node server.js  # log some misbehaving part of my app
```

LogFmt formats logs to be easily read by both humans and machines. If you've ever run `heroku logs --tail` you've seen logfmt formatted logs:

```
heroku[router]: at=info method=GET path="/" host=stormy-atoll-84913.herokuapp.com request_id=954756cb-5da7-450f-a17e-fbb75406ac28 fwd="69.132.5.125" dyno=web.1 connect=1ms service=498ms status=200 bytes=349
```

You can scan this yourself, but you can also send it through splunk, papertrail, etc.

The workflow for tracking down an error looks like:

1. Instrument the app with plenty of logs, which will be near-noops if the DEBUG flag doesn't select them. So you can just [leave them in all the time](https://github.com/expressjs/express/search?utf8=%E2%9C%93&q=debug&type=Code).
2. Enable logs for the part of the app that's being weird. On Heroku this looks like `$ heroku config:set DEBUG=fooApp:barComponent`.
3. Trigger the misbehavior or wait until requests are made that trigger it.
4. Use papertrail, splunk, whatever tool you like to track down the error.
5. Turn the logs back off (`$ heroku config:unset DEBUG`).

**Comment by tomdale** [comment]
This is super helpful, thanks @jmonster and @hunterloftis.
