### ISSUE TITLE
Fast boot and upstream bower dependencies

### ISSUE THREAD

**Issue by danjamin** [ember-fastboot/ember-cli-fastboot#133]
## Question

Are fastboot ember apps only able to use ember addons / components that are "fastboot ready"; in other words, do all ember addons have to custom support fastboot, or is there a way to expose global dependencies from the app using the addon?

## Example

I am using [ember-charts](https://github.com/addepar/ember-charts) which depends on `d3` and `lodash` via bower.  Everything works great without fastboot, but once I try to serve via fastboot I get `Reference Errors` around `d3`.

I attempted to whitelist via `fastbootDependencies` and even installed `d3` via npm to no avail.

**Comment by jfarlow** [comment]
Same.

I am using the bower component, [semantic-ui](https://github.com/Semantic-Org/Semantic-UI-Ember) and am getting `ReferenceError: jQuery is not defined` when trying to build using fastboot.  I don't believe much of jQuery is actually being used by the component though and it should (I think) in general be compatible with fastboot.

**Comment by fivetanley** [comment]
I would think lodash should in theory work out of the box. @tomdale we should investigate how we are creating the sandbox to allow for this. you should be able to add your own "global" in the sandbox.

As for jQuery, maybe we need a shim module so things continue to load (but blow up if you try to use the code as it won't work in fastboot mode).

**Comment by jasonmit** [comment]
> As for jQuery, maybe we need a shim module so things continue to load (but blow up if you try to use the code as it won't work in fastboot mode).

Mimicking the browser environment could lead to even more confusion.

If you need certain code paths to be ignored, such as those that depend on jQuery or D3 then it's recommended to guard against the fastboot environment using `isFastboot`

https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/app/services/fastboot.js#L13

**Comment by fivetanley** [comment]
> If you need certain code paths to be ignored, such as those that depend on jQuery or D3, then it's recommended to guard against the fastboot environment using the fastboot service's isFastBoot

This doesn't work as you can't wrap `import` statements in an `if`. This is why you would load a separate module (this does not create `window` or any other browser globals), it just returns allows jquery to continue loading and if you tried to use any code from it, it would blow up.

**Comment by jasonmit** [comment]
I understand the issue around importing modules that depend on browser APIs, but if these are bower deps you can prevent them from being included in the fastboot build by guarding around `app.import`.

Back to shimming, I'd just worry about the cost of having to maintain shims for all the popular current  and future libs.

**Comment by fivetanley** [comment]
I don't think a shim would be necessary, I think jQuery is able to load in node you just can't use any of the code right?

**Comment by jfarlow** [comment]
I'm here with a fairly ignorant technical position, more of a user's perspective: An error/failure on use of code would be more helpful than a failure to build because of a dependency.  When a failure/error points to code I can check it out, troubleshoot & work around the offending issues. When it just points to an 'illegal' dependency I'm pretty well out of options - and just straight have to give up working with fastboot.  Trying to strip all my code (and/or all of my dependency's code) of all jQuery references is an unforgiving task - which might be worth it - but I currently I can't evaluate/preview any of the benefits until I actual do the work.

**Comment by fivetanley** [comment]
Well, we can't really make all of jquery work in node. You can get around most of this by only using `$` inside of didInsertElement hooks. The problem with most jquery plugins is that they try to do stuff with the DOM when registering.

**Comment by fivetanley** [comment]
It's important to note that fastboot doesn't mean giving up jquery, but you have to be careful where you use it `didInsertElement` hooks only).

**Comment by jfarlow** [comment]
Again, I'm not particularly familiar with the infrastructure - would it be possible to indicate where in the code failures are happening or what kind of code can't be run?  Doing work to make a dependency fastboot compatible is not in itself a bad thing - I guess I just would have no idea how to go about doing it.

**Comment by fivetanley** [comment]
In theory you should get a stack trace when the code tries to load.

**Comment by fivetanley** [comment]
We'll be writing docs in the coming weeks on how to make an addon fastboot compatible.

**Comment by jfarlow** [comment]
That would be great.  Look forward to them.  I'll keep poking around and see what I can find.  More to learn by doing it anyway.

**Comment by tomdale** [comment]
@jfarlow and everyone, thanks for the feedback. It's very useful to have the perspective of a new user just getting started.

Ultimately we have a few different options in terms of trying to coerce JavaScript that was written for the browser to work in Node.js. None of them are great.

## Just Wait for Authors to Catch Up

"Universal" JavaScript is something more and more developers want, so there is market pressure to support running (or at least booting) in both environments. If app authors have trouble running their apps due to incompatible addons, we will tell them to submit a PR to the dependency to make it Node.js compatible.

This is probably the best solution, technically, but it sucks because it's extremely user-hostile.

## Disable Incompatible Addons Manually

Especially with Bower dependencies, make it easy for people to disable/not `app.import` dependencies in FastBoot builds. This is a pretty OK solution, but it sucks for two reasons:

1. It requires manual work.
2. It can break your app due to expected globals not existing, so now you need to add guards in your app code.

## Shim Addons

As discussed above, you can write an Ember-specific addon that wraps a Bower dependency and does the right thing. We can make this easier with tools for common cases, but this still sucks because now you have a shim that has to constantly track upstream, can easily fall out of date, and users have to know to use it. Also, ideally things "just work" with Ember—we want to teach developers that they can participate in the greater JS ecosystem, not have to wait for an Ember-specific version to use something.

## Try to Trick Addons

We can try to simulate enough of a browser environment by stubbing out globals that addons can at least boot. For example, we do this today by exposing a `window` global because so. much. code. assumes that it exists. But this quickly breaks down because so many dependencies do things like feature detection _at eval time_, which often relies on `document.createElement()`. So this might help some cases, and maybe we can do it in a targeted way for very popular libraries, but it's extremely brittle and not going to solve the whole problem.

## Use jsdom

We could offer an addon that installs `jsdom` into the FastBoot sandbox. This should solve most cases of addons failing on boot, but kind of defeats the entire point of FastBoot. Still, it is a possibility we should consider for helping people migrate.

---
@jfarlow:

> When it just points to an 'illegal' dependency I'm pretty well out of options - and just straight have to give up working with fastboot. Trying to strip all my code (and/or all of my dependency's code) of all jQuery references is an unforgiving task - which might be worth it - but I currently I can't evaluate/preview any of the benefits until I actual do the work.

Can you say more about this? I don't think there's anything that says "illegal dependency." You should definitely get a stack trace where the library in question was trying to access `document` or `localStorage` or something.

**Comment by jfarlow** [comment]
Regarding "illegal dependencies" - I think this is specific to the semantic UI bower shim.  It seems to be passing 'jQuery' itself through the function, or some reference to it.  So a stack trace is given, but it's not particularly useful to me, as it's not a common usage pattern.  I'm not well-versed enough to figure out how where the 'jQuery' variable is being called/passed to/from.  Sorry to not be more helpful there.  Don't worry about that particular issue.  I'll figure it out eventually.

Regarding the larger issue for FastBoot:
For me, "Wait" & "Disable" are the best options. The ability to just 'disable' or otherwise bypass whatever errors I would receive, and otherwise 'try out' FastBoot even with failed components would be very useful. And if I get sufficient benefit from FastBoot, while breaking a few UI things, and I still want the plugins to work, I'll become an advocate in pushing other authors forward in the "Wait" option.  

In general, FastBoot is interesting enough, and obviously different enough that I don't mind not having shims and helpers.  I would like to have easy ways to escape 'old-looking' code though so that I can figure out how to write guards.  The added benefit here is that once I know how/why/where guards need to be added, I both get a feel for what FastBoot is doing, and for what I need to ask of my dependencies (what they should have, and what they should avoid).  Right now I do not even know how to disable particular dependencies alone, what a guard would look like, nor where to put them, so I can't even try FastBoot.

**Comment by ewoutp** [comment]
I have the same semantic-ui problem reported above.
(Also made an issue there https://github.com/Semantic-Org/Semantic-UI-Ember/issues/100)

Any suggestions how to workaround/fix this?

**Comment by tomdale** [comment]
@ewoutp That one's a little trickier, because disabling the addon entirely would cause your templates to error (due to not being able to find the components). I think the best bet there may be to temporarily use a fork of the library that doesn't import the base Semantic-UI library in FastBoot mode.

**Comment by ewoutp** [comment]
@tomdale thanks, but I have one question.
"use a fork of the library that doesn't import the base Semantic-UI library in FastBoot mode" how do I do that?

**Comment by tomdale** [comment]
@ewoutp Oops, sorry I missed this. See https://github.com/ember-fastboot/ember-cli-fastboot/issues/134#issuecomment-197540068 for how to selectively import addons.
