### ISSUE TITLE
FastBoot and waiting for additional asynchronous content

### ISSUE THREAD

**Issue by danmcclain** [ember-fastboot/ember-cli-fastboot#138]
## Summary
There are times that you'd want ember to load data asynchronously in the browser. This changes when in FastBoot, you have a single pass before the response is sent back to the browser, and there is no updating the source once the response is sent when it comes to crawlers. Some content you may want index may be loading asynchronously in the Ember app, but needs to be there for crawlers

## FastBootInfo.deferRendering(promise)
By adding a method to chain promises to the FastBoot service, we can allow the user to notify FastBoot which promises this page depends on before rendering. The server would then wait for this promise to resolve after hitting the `visit` method of the app, so that all the routes/components/etc could notify the server. This would be an explicit call to `fastboot.deferRendering`.

## Additional consideration
Should this be done for all ember-data calls automatically in FastBoot-land. There is an argument in both directions. This would ensure that all ember-data calls are completed before rendering the page, which would cover the majority of use cases for the typical user. Instead of having to check to see if we are in FastBoot and then explicitly call deferRendering, we could hook into ember-data to do this automatically.

Instead of hooking into ember data, we could provide an additional hook to the route, akin to a `fastBootModel` which will be expected to return a promise that should block the rendering of the page until.

### Drawbacks from ember-data and hooks approaches
Both the ember-data approach and fastBootModel hook approach would prevent the user from doing their own checks of whether or not they are in FastBoot and handle that case appropriately, but bring in addition work. And there may be cases in the ember-data approach that you would not want to wait for every ember-data operation to resolve before allowing FastBoot to return the response.

/cc @tomdale @ef4

**Comment by tomdale** [comment]
Is there a benefit to having a FastBoot-specific API instead of just returning a blocking promise from e.g. `afterModel()`?

**Comment by danmcclain** [comment]
I'm not sure if something like liquid fire needs something like this to let fastboot know when the animations are done. I know @ef4 had originally brought up the idea of the promise based method of deferring rendering

I was thinking of the case where you may want content to not block in the browser so that you can display a page before the additional content (like a sidebar of related items)

The other case is when you don't use the blocking `model/afterModel` hooks in your application to begin with. I know there are applications that do their ajax requests in their setupController, or return a non-promise object from the model hook and then handle the loading of content in the template

**Comment by ef4** [comment]
liquid-fire is adequately handled in the vast majority of cases -- you have to go out of your way to make it animate during initial render.

Likewise, I tend to strongly recommend that people use routes to load most asynchronous things, even in the case where they have some parts of the page that should render instantly. (You can always split the route into a child route that has asynchronous dependency and a parent that doesn't.)

That still leaves some legitimate cases where people are doing asynchronous things in components, like when there are multiple independent sections that need async data or deliberate animations at initial render. This is not unlike the situation in tests, where `registerWaiter` (and hopefully soon the newer replacements for that in the testing unification RFC) is the way that arbitrary asynchronous capabilities can be declared.

We may want to try to unify with that API. Right now it's still proposed to be polling-based instead of promise-based, but making it cover the fastboot case may be worth altering it.

**Comment by tomdale** [comment]
> I was thinking of the case where you may want content to not block in the browser so that you can display a page before the additional content (like a sidebar of related items)

@danmcclain Right, but what I'm saying is, couldn't you just say something like:

```js
let promise = this.store.find('article', params.article_id);

if (isFastBoot) {
  promise = promise.then(waitForSidebar);
}

return promise;
```

This would achieve the same effect without introducing a new API, and seems ~the same level of complexity.

**Comment by danmcclain** [comment]
@tomdale I see what you mean, that would be the same complexity. That only leaves how we should address @ef4's point around components that have their own requests

**Comment by tomdale** [comment]
@danmcclain Ah, of course. I forgot about that use case.

**Comment by markmhx** [comment]
Has there been any work done to support components that load data asynchronously with FastBoot since this issue was closed?

On routes with more than one clear model, I much prefer to use components that load their own data asynchronously, to maximize modularity and support progressive, non-blocking screen loading. 

But I'm finding it pretty difficult to come up with an elegant solution for such components within FastBoot since FastBoot renders them before they've loaded their data by default, and I'm getting into a tangled mess trying to expose data-loading hooks on components that routes could call within the route's `model` (or `afterModel`) hook when loaded by FastBoot (making their loading effectively synchronous and triggered by the route itself only in the FastBoot context).

I'm not sure if instead of creating special FastBoot hooks, it may be wiser to evolve FastBoot to support delayed rendering until all async-tagged components (e.g. those with a property like `async` marked as `true`?) have reported their loaded state via some sort of event call, perhaps on the `fastboot` service itself (e.g. `this.get('fastboot').componentReady()`)?

Sorry if there's a better place to post this inquiry. This is the most relevant issue I've found even though it's closed.

**Comment by markmhx** [comment]
In case anyone finds this thread through search and is looking for a similar solution, @kratiahuja pointed me toward the `deferRendering` method on the FastBoot service.

The following is an example of how to use it to accomplish the above (thanks @danmcclain!):

https://github.com/ember-fastboot/ember-cli-fastboot/blob/2e913eb907d3a8aa2b64d87b2877704a365fa6bf/test/fixtures/async-content/app/components/async-content.js

**Comment by courthead** [comment]
@markmhx Question about your use-case: How do you prevent the user experience of deferring rendering in components from being jarring? For example:

1. Rendering is deferred on the server so the component can load and display its content.
2. Browser receives the HTML showing the fully-rendered component.
3. Ember boots up, redraws the app, and your component which looked done now has to reload its data.

The only solution I can find around this is to just load all the data in the route's hooks, which takes away the point of `deferRendering`.

**Comment by markmhx** [comment]
@courthead Good question, and I think the short answer is Shoevox: https://github.com/ember-fastboot/ember-cli-fastboot#the-shoebox

After implementing deferredRendering with my components, I started experiencing the redrawing problem you describe with [my site](http://markmhendrickson.com). I need to try implementing Shoevox to know for sure, but I think with a standard implementation, it should prevent the reloading of data and subsequent redrawing.
