### ISSUE TITLE
Asset in template is not fingerprinted in production

### ISSUE THREAD

**Issue by topaxi** [ember-fastboot/ember-cli-fastboot#141]
Using current ember-cli-fastboot master.

If I have a template with an image, it refers to the unfingerprinted asset.

Input:
```hbs
<img src="/assets/foo.png">
```

Output:
```hbs
<img src="/assets/foo.png">
```

Expected:
```hbs
<img src="/assets/foo-SomeHash.png">
```

See: [topaxi.ch](https://topaxi.ch/) The `puzzle.png` image
Or the repository: https://github.com/topaxi/topaxi.ch

Once the the page loads, the browser build correctly uses the fingerprinted asset.

**Comment by thejase** [comment]
Experiencing this same issue.  Build strategy:

```
ember build --environment=production # builds to /dist
ember fastboot --environment production --port=1234 --serve-assets
```

**Comment by jasonmit** [comment]
https://github.com/tildeio/ember-cli-fastboot/blob/master/lib/broccoli/fastboot-build.js#L35

It's only asset revving over the javascript tree, so it doesn't take into account anything in the public tree which is why it misses `foo.png`.  I worked around this by including the full `emberApp.proto.toArray` `sourceTree`.  That's when I also uncovered that everything in the root of `/public` (robots.txt, crossdomain.xml, etc.) isn't served up by the fastboot server.

Unsure how to resolve this without resolving the new bug I stumbled on.

**Comment by thejase** [comment]
The workaround I found was just to build using a non-production mode.  Unfortunately, this removes build signatures from all assets, so we have to resolve back to browser caching, which is at least one refresh behind, no matter your caching strategy.

**Comment by ebryn** [comment]
Removing `broccoli-asset-rev` from your package.json is a quick and easy workaround for now.

**Comment by ballPointPenguin** [comment]
not sure if this is the same issue, but I see 404s on my fingerprinted css and js assets despite the fact that the ember app is running correctly
