### ISSUE TITLE
Improve fastboot service public API

### ISSUE THREAD

**Issue by locks** [ember-fastboot/ember-cli-fastboot#154]
Currently the public API of the fastboot service only exposes the host, but I'm developing the new guides viewer and I'd like to access the pathname to do some i18n shenanigans.

@danmcclain can help me fill out the issue with more detail.

**Comment by danmcclain** [comment]
We should probably include access to the query string in the service as well

The FastBootInfo class in `ember-fastboot-server` should provide a consistent, server (ie Express) agnostic API so that the server can swap backends without modifying the public API

ember-cli-fastboot's `fastboot` service consumes `FastBootInfo`, so the API here will be closely tied to it

**Comment by danmcclain** [comment]
We fleshed out the `response`/`request` api in the `fastboot` service
