### ISSUE TITLE
why not leave `configInMeta: true`

### ISSUE THREAD

**Issue by stefanpenner** [ember-fastboot/ember-cli-fastboot#160]
Seems like the fastboot server could just provide meta before, in-fact meta being configurable might be a great way for fastboot to quickly change options on the fly, without needing a recompile.

**Comment by fivetanley** [comment]
I'm not sure what this means

**Comment by stefanpenner** [comment]
https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L40-L41

**Comment by krisselden** [comment]
I suggested this same thing, the sandbox should provide the config, not on the server the config is built in.

**Comment by krisselden** [comment]
One issue though with leaving it exactly the same path is `Ember['default'].$('meta[name="' + metaName + '"]').attr('content')` is not going to work with simple-dom and simple-dom can't provide document as a global because too many libraries check this to mean "I'm in a browser"

We'd still need branching in the evironment module but it should be `if (server) { configFromSandbox() } else { configFromMeta() }`

**Comment by stefanpenner** [comment]
> Ember['default'].$('meta[name="' + metaName + '"]').attr('content')

ya the bootstrap code will need to be changed, I suspect something as @krisselden should do the trick.

**Comment by tomdale** [comment]
I think this should be next on our list of things to work on since it's a potentially breaking change that we should get done before 1.0. Should be pretty easy to save the config info in `fastboot/package.json` and have the app read from the `FastBoot` global instead of scanning the DOM.

The only thing I'm not sure of is if there's a way to patch this from an addon or if we will need to make changes to Ember CLI to support it.
