### ISSUE TITLE
Possible Memory Leak with ember-cli 2.10 and ember-cli-emblem

### ISSUE THREAD

**Issue by PrinceCornNM** [ember-fastboot/ember-cli-fastboot#289]
I found that memory use consistently grows when a page refresh occurs with 2 of my fastboot apps. Originally, I looked into various particulars about those apps to try to see what could be the culprit. I found that I was able to reproduce the issue in this [dummy app](https://github.com/PrinceCornNM/fastboot-mem-leak). I was able to use this dummy app by running `ember fastboot --serve-assets` with node 6.5.0 to increase memory use by a couple mbs after each page refresh.

Although, I believe this is not related both of my apps use the fastboot-express-middleware in case that might be of any use.

**Comment by vkoves** [comment]
I was able replicate this issue by cloning the dummy app and holding **F5** to spam requests to the local server, and memory went up really quickly. Even after I stopped sending additional requests, the app stayed at its high memory usage (I got it to ~900 MB and then stopped sending requests). If I run the app with EmberJS without Fastboot, using `ember s`, I did not encounter these problems.

**Comment by kratiahuja** [comment]
I assume you are seeing the memory usage for your app running browser and not for the app running in Node? Is that true? If so, there is really nothing different that happens in browser for fastboot or any other ember app.

**Comment by PrinceCornNM** [comment]
The memory growth is occurring in Node and I'm trying to see if its an issue with garbage collection or something like that.

**Comment by kratiahuja** [comment]
So two things that we should figure out is:
1. Is it the fastboot lib or the sandbox that is leaking the memory?
2. Is the express middleware layer that is leaking the memory that is serving the assets causing the leak?

The reason I am saying this is because with `ember serve` your base page is simply served by the Node process (express middleware in built in `ember-cli`) as against in Fastboot a different express middleware serves the base page and loads the application in Node process too for server side rendering. Would be nice to slice the two differently to figure out the root cause.

**Comment by ryanone** [comment]
Just curious, since you're using Emblem (and the current hunch is it's Emblem-related), have you tried comparing the transpiled output produced by ember-cli-emblem against a similar Handlebars template?

**Comment by PrinceCornNM** [comment]
@ryanone Its not related to ember-cli-emblem because without the package the issue is still there.
@kratiahuja I will push a commit with memwatch and heapdump as a part of a express server in order to try to test using the fastboot-express-middleware to find the leak. I will also try to start gathering more data to find the root issue.

**Comment by PrinceCornNM** [comment]
After testing with node 4.6.2 I found the memory leak is quite worse. I think Node 6 does a better job at garbage collection with this test app.

**Comment by kratiahuja** [comment]
@PrinceCornNM can you draw a graph of this with the different node versions?

Also did you get a chance to see if it was the fastboot command or app leaking?

**Comment by PrinceCornNM** [comment]
@kratiahuja I made a node launch script for the [dummy app](https://github.com/PrinceCornNM/fastboot-mem-leak), and I think that the app on its own isn't leaking because it only leaks if I use the fastboot-express-middleware.

**Comment by t4t5** [comment]
I think I have encountered the same issue in my app. No solution so far. https://github.com/ember-fastboot/fastboot-app-server/issues/31

**Comment by PrinceCornNM** [comment]
Hey,  so I found a work around to the memory leak issue with fastboot.
I was able to make a work around for this problem by making fastboot not create a new instance for each visit and instead reuse an already existing instance. So I just keep an ember instance instead of destroying and rebuilding ember instances each time. Although this does fix my memory leak issue, I would guess there could be problems with doing this.

I ended up with this: https://github.com/PrinceCornNM/fastboot

If this is any good I would probably rewrite these commits and try to preserve this to preserve the old functionality and just make this an option.

**Comment by kratiahuja** [comment]
I don't think that workaround will work when you have concurrent requests.

**Comment by pmelnichuk** [comment]
Any update on this ticket / has anyone attempted to debug the memory profiles / any updates to go on from here?

**Comment by tomdale** [comment]
I documented my steps for trying to track down memory leaks here: https://github.com/ember-fastboot/fastboot/pull/100#issuecomment-275805511. So far I haven't been able to find any in the FastBoot code itself, and other cases have been due to a leak in application code that the long-lived nature of FastBoot makes more apparent.

You can also use http://github.com/kellyselden/fastboot-pool to automatically monitor FastBoot processes and kill them once their memory passes a certain threshold.

I'm going to close this issue as it seems to have gone stale, but if we have any more leads on possible culprits that aren't app-specific, please feel free to file a new issue.
