### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by zion03** [ember-fastboot/ember-cli-fastboot#343]
I have error `ReferenceError: jQuery is not defined`and as I understand it's a famous question.
One of the solutions is remove this addons in fastbot mode as discussed in #134
But I don't understand how to restrict loading addon with auto-loading 

like:
```
module.exports = {
  name: 'ember-fullcalendar',
  included: function(app) { 
...
```

I'm not using `app.import` in ember-cli-build.js

**Comment by rizkysyazuli** [comment]
Pls forgive me for asking this question again. But since i haven't found a clear answer, i just have to post this again.

I'm using Flexslider, a jQuery plugin installed via Bower. This plugin is included via `app.import()` in `ember-cli-build.js` and now it's complaining about missing jQuery.

How do i exclude this plugin from Fastboot?

**Comment by buschtoens** [comment]
https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/README.md#disabling-incompatible-dependencies

Dies this help you out? 😉

**Comment by kratiahuja** [comment]
Please note currently we don't have declarative APIs for excluding libraries in `ember-cli-build.js` (assuming you meant your app). Please create an in-repo addon and use the link @buschtoens provided.

**Comment by rizkysyazuli** [comment]
@buschtoens thx. will look into it.
