### ISSUE TITLE
`SyntaxError: Unexpected token` occurs with nullish collascing operator

### ISSUE THREAD

**Issue by ijlee2** [ember-fastboot/ember-cli-fastboot#764]
## Description

Hello, I'm running into a build error that involves FastBoot. I may have encountered an issue similar to https://github.com/ember-fastboot/ember-cli-fastboot/issues/746.

I have 2 apps that use `ember-container-query@1.0.1`. The addon uses nullish coalescing operator `??`, introduced in ECMA 2020.

One of the apps uses FastBoot (v2.2.1), and the other does not. When I updated `ember-container-query` to v1.0.3 (the only change in the addon was updating `ember-cli-babel` from v7.20.0 to v7.20.5):

- The app that uses FastBoot resulted in an error when I visited `localhost:4200`.
- The app that doesn't use FastBoot continued to run okay.
- The app that uses FastBoot ran okay when I visited `localhost:4200?fastboot=false`.

Updating `ember-cli-fastboot` to v2.2.3 didn't solve the problem.

## Error log

```
/var/folders/2z/93zyyhx13rs879qr8rzyxrb40000gn/T/broccoli-689520dxo26a682Mz/out-529-broccoli_merge_trees/assets/vendor.js:121232
      return this.args.features ?? {};
                                 ^

SyntaxError: Unexpected token '?'
    at new Script (vm.js:88:7)
    at VMSandbox.eval (/my-app/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /my-app/node_modules/fastboot/src/ember-app.js:190:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/my-app/node_modules/fastboot/src/ember-app.js:187:21)
    at EmberApp.retrieveSandboxedApp (/my-app/node_modules/fastboot/src/ember-app.js:235:10)
    at new EmberApp (/my-app/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/my-app/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/my-app/node_modules/fastboot/src/index.js:52:10)
    at /my-app/node_modules/ember-cli-fastboot/index.js:330:29
```

## Related links

- https://github.com/ijlee2/ember-container-query/blob/master/addon/components/container-query.js#L11-L21
- https://eslint.org/blog/2020/06/eslint-v7.2.0-released

**Comment by ijlee2** [comment]
I started a conversation on Discord so there may be future replies that can provide additional insight:

- [`#topic-addon-development` channel](https://discordapp.com/channels/480462759797063690/491905849405472769/725409742759133285)
- [`#fastboot` channel](https://discordapp.com/channels/480462759797063690/485861149821239298/725418793203138641)

**Comment by SergeAstapov** [comment]
@ijlee2 We had same issue and I think it has nothing to do with FastBoot.

nullish coalescing operator is JavaScript feature, which is supported in Node.js 14+, Chrome 80+, Firefox 72+.

*I assume* you use default setup in `config/targets.js` (which has `last 1 Chrome versions` in [blueprint](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/targets.js#L4)) and Node.js older than v14?

In general, you should specify minimum Chrome version in `config/targets.js` that has same underlying V8 as Node.js version you use.

As an example, if you use Node v12.16.1 (LTS) - it has v8 version 7.8.279, which is used in Chrome 78.0.3904 [per wiki](https://en.wikipedia.org/wiki/Google_Chrome_version_history), so your `config/targets.js` should be updated to use `Chrome 78` instead of `last 1 Chrome versions`.

Also, it should not be a problem in production build as default [blueprint](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/config/targets.js#L4) has `ie 11` as compilation target.

**Comment by ijlee2** [comment]
## Update to the issue

Thanks to @SergeAstapov (as well as @jaredgalanis and @mansona), I got to learn more about how target builds work today.

I can confirm that specifying `'Chrome 78'` (I went with `'Chrome >= 78'` in the end) in my app's `config/targets.js` helped the build error go away. 🎉

In case people may find this site useful, I used [caniuse's usage matrix](https://caniuse.com/usage-table) to help decide which minimum version to support for other browsers.

On Discord, @SergeAstapov mentioned:

> I think it would be helpful to mention in `ember-cli-fastboot` docs that compilation targets should be set with notion of Node.js version being used for the app.

I think it would be helpful as well, especially for developers who aren't experienced with FastBoot like me. At any rate, I think this issue can be closed for now.

Thanks again to everyone for the help!

**Comment by st-h** [comment]
### More updates

I was running into the same issue and Chris Manson suggested a much nicer solution. One needs to add `node: 'current'` to `targets.js`: 

```
'use strict';

const browsers = [
  'last 1 Chrome versions',
  'last 1 Firefox versions',
  'last 1 Safari versions'
];

const isCI = !!process.env.CI;
const isProduction = process.env.EMBER_ENV === 'production';

if (isCI || isProduction) {
  browsers.push('ie 11');
}

module.exports = {
  browsers,
  node: 'current'
};
```


https://discuss.emberjs.com/t/help-needed-the-data-argument-must-be-of-type-string-or-an-instance-of-buffer-typedarray-or-dataview-received-an-instance-of-node/18061/7?u=hummingbird
