### ISSUE TITLE
Wrong env in /tests while running `ember server`

### ISSUE THREAD

**Issue by zeppelin** [ember-fastboot/ember-cli-fastboot#80]
Symptom:

1. `http://localhost:4200/tests` is incorrectly in `development` mode while running `ember server`
1. `http://localhost:4200/tests` is correctly in `test` mode while running `ember test --server`

If `ember-cli-fastboot` is removed from `package.json`, the erroneous behavior disappear.

```
$ ember -v
version: 2.2.0-beta.1
node: 0.12.1
npm: 2.14.10
os: darwin x64
```

**Comment by rwjblue** [comment]
This is due to the usage of storeConfigInMeta usage: 

    app.options.storeConfigInMeta = false;

From here: https://github.com/tildeio/ember-cli-fastboot/blob/master/index.js#L47

---

By default storeConfigInMeta is true, but ember-cli-fastboot forces it to be false (for all commands). We need it to be false for commands related to fastboot, but we may be able to change that override to only apply when running a fastboot related command. 

Would you mind submitting a PR moving that assignment up into the guard just above?

**Comment by zeppelin** [comment]
Done, if that's what you meant. Looks like it was inside the guard [at a certain point](https://github.com/tildeio/ember-cli-fastboot/commit/1ab7cc220eae779ea601bae542dad0e3341a8add).

**Comment by rwjblue** [comment]
HA! Yeah, I knew I remembered doing it differently initially. :smile_cat:

**Comment by zeppelin** [comment]
This was the commit that changed the behavior: https://github.com/tildeio/ember-cli-fastboot/commit/2618e9fa486ad5bd4bd61994740b100405748823

Do you think this may be still valid?

**Comment by tomdale** [comment]
This should be fixed now.
